pimcore:
    objects:
        class_definitions:
            data:
                map:
                    permissionManyToOneRelation: FrontendPermissionToolkitBundle\CoreExtensions\ClassDefinitions\PermissionManyToOneRelation
                    permissionManyToManyRelation: FrontendPermissionToolkitBundle\CoreExtensions\ClassDefinitions\PermissionManyToManyRelation
                    permissionResource: FrontendPermissionToolkitBundle\CoreExtensions\ClassDefinitions\PermissionResource
                    dynamicPermissionResource: FrontendPermissionToolkitBundle\CoreExtensions\ClassDefinitions\DynamicPermissionResource
